### ISSUE TITLE
IOS  archive build failed

### ISSUE THREAD

**Issue by 17600774441** [MythiCode/flutter_camera_kit#10]
ld: warning: ignoring file /Volumes/project/Project/cameraflutter/ios/Pods/MLKitBarcodeScanning/Frameworks/MLKitBarcodeScanning.framework/MLKitBarcodeScanning, missing required architecture armv7 in file
    /Volumes/project/Project/cameraflutter/ios/Pods/MLKitBarcodeScanning/Frameworks/MLKitBarcodeScanning.framework/MLKitBarcodeScanning (2 slices)
    ld: warning: ignoring file /Volumes/project/Project/cameraflutter/ios/Pods/MLKitCommon/Frameworks/MLKitCommon.framework/MLKitCommon, missing required architecture armv7 in file
    /Volumes/project/Project/cameraflutter/ios/Pods/MLKitCommon/Frameworks/MLKitCommon.framework/MLKitCommon (2 slices)
    ld: warning: ignoring file /Volumes/project/Project/cameraflutter/ios/Pods/MLKitVision/Frameworks/MLKitVision.framework/MLKitVision, missing required architecture armv7 in file
    /Volumes/project/Project/cameraflutter/ios/Pods/MLKitVision/Frameworks/MLKitVision.framework/MLKitVision (2 slices)

**Comment by 17600774441** [comment]
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_MLKBarcode", referenced from:
      objc-class-ref in camerakit(CameraKitFlutterView.o)
  "_OBJC_CLASS_$_MLKVisionImage", referenced from:
      objc-class-ref in camerakit(CameraKitFlutterView.o)
  "_OBJC_CLASS_$_MLKBarcodeScanner", referenced from:
      objc-class-ref in camerakit(CameraKitFlutterView.o)
  "_OBJC_CLASS_$_MLKBarcodeScannerOptions", referenced from:
      objc-class-ref in camerakit(CameraKitFlutterView.o)
ld: symbol(s) not found for architecture armv7

**Comment by hrshs** [comment]
According to the ml-kit documentation, ML Kit does not support 32-bit architectures (i386 and armv7). ML Kit does support 64-bit architectures (x86_64 and arm64). 
You should remove armv7 from your architecture at build settings for release mode.
