### ISSUE TITLE
Android take picture not working

### ISSUE THREAD

**Issue by roitnaidu23** [MythiCode/flutter_camera_kit#4]
Please can you check the take picture does not return the image url, does it need storage permission? or any extra setup

**Comment by hrshs** [comment]
Camera kit doesn't need to any extra permission for taking picture. What's your phone?
Some phones with camera api 2 doesn't work like some Samsung old s series. You can set  `useCamera2API` false in this phones.

**Comment by roitnaidu23** [comment]
I am using Pixel 3. I saw in documentation that you need to set the `hasBarcodeReader` to false to take pictures. But my use case was to take pictures of barcode scans, may be you could include this in future updates to take pictures while scanning.

**Comment by hrshs** [comment]
The new version released. For android phones, you can take pictures while scanning barcodes in `API_X` mode. This feature is not supported on iOS phones yet, but we will work on it.
