### ISSUE TITLE
How to choose front camera

### ISSUE THREAD

**Issue by natgross** [MythiCode/flutter_camera_kit#5]
It's working ok for me, but only with the rear camera. I went thru the example, and the api, but I cannot figure out how to get it to use the front (selfie) camera.
Thanks
nat

**Comment by hrshs** [comment]
This feature is not supported yet, we're going to work on it in the near future.

**Comment by hrshs** [comment]
The new version is released. You can set the front camera for taking pictures and scanning barcodes.
