### ISSUE TITLE
takePicture file name

### ISSUE THREAD

**Issue by natgross** [MythiCode/flutter_camera_kit#6]
How can I specify the jpg path for takePicture()? Currently it uses something like data/user/0/com.myApp_name/cache/pic.jpg.
But that folder is non existent in many devices. I simply want to pass any path for the target jpg to the takePicture() method.
Thanks.

**Comment by hrshs** [comment]
This feature is not supported yet, we're going to work on it in the near future.

**Comment by hrshs** [comment]
version 0.0.75 was released. You can pass your custom path to save images.
